#!/bin/bash

echo "========================="
echo "ClaimLinker START"
echo "========================="
rm -f apache-tomcat-9.0.34/webapps/ClaimLinker.war
mvn clean validate compile test package verify war:exploded -f pom.xml
cd target/ClaimLinker-1.0-SNAPSHOT
jar -cvf ../ClaimLinker.war WEB-INF
cd ..
cp ClaimLinker.war ../apache-tomcat-9.0.34/webapps
cd ..
apache-tomcat-9.0.34/bin/catalina.sh start
if [ ! "$(docker ps -a -q -f name=ES_single)" ]; then
  docker run -p 9200:9200 -p 9201:9201 -d --env discovery.type=single-node --name ES_single docker.elastic.co/elasticsearch/elasticsearch:7.6.2
else
  docker start ES_single
fi
echo "ElasticSearch Server has started...!"
