# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ClaimLinker CI

on:
  push:
    branches: [ master , Windows ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Go to the FEL's directory
        run: chdir=/ClaimLinker_commons/FEL-master
      - name: package-install FEL to ClaimLinker's libraries
        run: mvn install:install-file -Dfile=lib/FEL-0.1.0-fat.jar -DgroupId=com.yahoo.FEL -DartifactId=FEL -Dversion=0.1.0 -Dpackaging=jar -DgeneratePom=true
      - name: Go to the Claimlinker root directory
        run: chdir=/ClaimLinker_commons/FEL-master
      - name: Build
        run: mvn package -f pom.xml;
