name: ClaimLinker CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Go to the FEL's directory
        run: chdir=/ClaimLinker_commons/FEL-master
      - name: Build FEL and package-install to ClaimLinker's libraries
        run: >-
          mvn package install:install-file -Dfile=target/FEL-0.1.0-fat.jar
          -DgroupId=com.yahoo.FEL -DartifactId=FEL -Dversion=0.1.0
          -Dpackaging=jar -DlocalRepositoryPath=../lib
      - name: Go to the Claimlinker root directory
        run: chdir=/ClaimLinker_commons/FEL-master
      - name: Build
        run: mvn package -f pom.xml;
